language: node_js
node_js:
- 10
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
script:
- npm test
after_success:
- bash .travis.deploy.sh
before_deploy:
- ls -al dist/
- cd dist
deploy:
  provider: npm
  email: mat@mlefree.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
